version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      docker: 18
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USER} --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - npm run lint
      - cd packages/ecs_service && npm run build
      - cd ../lambda_service && npm run build
      - cd ../cloudfront_service && npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ../ecs_service && npm run deploy
      - cd ../lambda_service && npm run deploy
      - cd ../cloudfront_service && npm run deploy
      
artifacts:
  files:
    - '**/*'