version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      docker: 18
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USER} --password-stdin
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run lint
      - lerna run build
  post_build:
    commands:
      - echo Build completed on `date`
      - lerna run deploy
      
artifacts:
  files:
    - '**/*'