version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp packages/cloudfront_service/index.html s3://junhyung-test-web --acl public-read
      - cd packages/lambda_service/ && zip index.zip index.js
      - aws lambda update-function-code --function-name lambda-svc --zip-file file://index.zip
artifacts:
  files:
    - '**/*'